#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR_DEFAULT="$(cd "$SCRIPT_DIR/.." && pwd)"

real_home() {
  if [[ -n "${HERMES_REAL_HOME:-}" ]]; then
    printf '%s\n' "$HERMES_REAL_HOME"
  elif [[ -n "${USER:-}" && -d "/home/$USER" ]]; then
    printf '%s\n' "/home/$USER"
  else
    printf '%s\n' "${HOME:?HOME is not set}"
  fi
}

REAL_HOME_DEFAULT="$(real_home)"
PREFIX_DEFAULT="$REAL_HOME_DEFAULT/.local"
ENV_FILE_DEFAULT="$REAL_HOME_DEFAULT/.hermes/kanban-webui.env"

PREFIX="$PREFIX_DEFAULT"
APP_DIR="$APP_DIR_DEFAULT"
ENV_FILE="$ENV_FILE_DEFAULT"
DRY_RUN=0
SKIP_UV_SYNC=0

usage() {
  cat <<'USAGE'
Install Hermes KanbanWebUI helper commands for a local clone.

Usage:
  ./scripts/install.sh [options]

Options:
  --dry-run              Print actions without writing files
  --prefix PATH          Install wrapper to PATH/bin; default ~/.local
  --app-dir PATH         HermesKanban checkout path; default current repo
  --env-file PATH        Env file path; default ~/.hermes/kanban-webui.env
  --skip-uv-sync         Do not run uv sync
  -h, --help             Show help

Installs:
  ~/.local/bin/hermes-kanban
  ~/.hermes/kanban-webui.env

Important env values:
  HERMES_KANBAN_WEBUI_APP_DIR
  HERMES_AGENT_ROOT
  HERMES_KANBAN_WEBUI_HOST
  HERMES_KANBAN_WEBUI_PORT
USAGE
}

log() {
  echo "$*"
}

run() {
  if [[ "$DRY_RUN" == "1" ]]; then
    echo "DRY RUN: $*"
  else
    "$@"
  fi
}

write_env_file() {
  local env_dir
  env_dir="$(dirname "$ENV_FILE")"
  run mkdir -p "$env_dir"
  if [[ -f "$ENV_FILE" ]]; then
    log "Keeping existing env file: $ENV_FILE"
    return
  fi
  if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY RUN: create $ENV_FILE from .env.example"
    return
  fi
  cat > "$ENV_FILE" <<EOF
# Hermes KanbanWebUI local configuration
# Generated by scripts/install.sh. Values are shell syntax and are sourced by hermes-kanban.

HERMES_REAL_HOME="$REAL_HOME_DEFAULT"
HERMES_KANBAN_WEBUI_APP_DIR="$APP_DIR"
HERMES_AGENT_ROOT="\${HERMES_REAL_HOME}/.hermes/hermes-agent"

HERMES_KANBAN_WEBUI_HOST=127.0.0.1
HERMES_KANBAN_WEBUI_PORT=8790
HERMES_KANBAN_WEBUI_STATE="\${HERMES_REAL_HOME}/.hermes/kanban-webui"
HERMES_KANBAN_WEBUI_LOG="\${HERMES_REAL_HOME}/.hermes/logs/kanban-webui.log"

# Optional: require X-Kanban-Token or Authorization: Bearer for /api/*.
HERMES_KANBAN_WEBUI_TOKEN=

# Optional: comma-separated hostnames allowed by Host-header validation.
HERMES_KANBAN_WEBUI_ALLOWED_HOSTS=
EOF
  chmod 600 "$ENV_FILE"
  log "Created env file: $ENV_FILE"
}

check_python() {
  command -v python3 >/dev/null 2>&1 || { echo "python3 not found" >&2; exit 1; }
  python3 - <<'PY'
import sys
if sys.version_info < (3, 11):
    raise SystemExit('Python 3.11+ is required')
PY
}

check_uv() {
  if ! command -v uv >/dev/null 2>&1; then
    echo "uv not found. Install uv first: https://docs.astral.sh/uv/" >&2
    exit 1
  fi
}

check_app_dir() {
  [[ -f "$APP_DIR/server.py" ]] || { echo "server.py not found in --app-dir: $APP_DIR" >&2; exit 1; }
  [[ -f "$APP_DIR/pyproject.toml" ]] || { echo "pyproject.toml not found in --app-dir: $APP_DIR" >&2; exit 1; }
}

warn_hermes_missing() {
  if command -v hermes >/dev/null 2>&1; then
    log "Hermes CLI found: $(command -v hermes)"
  elif [[ -f "$REAL_HOME_DEFAULT/.hermes/hermes-agent/hermes_cli/kanban_db.py" ]]; then
    log "Hermes Agent checkout found: $REAL_HOME_DEFAULT/.hermes/hermes-agent"
  else
    log "WARN: Hermes was not found on PATH and $REAL_HOME_DEFAULT/.hermes/hermes-agent is missing."
    log "      Install Hermes first, or edit HERMES_AGENT_ROOT in $ENV_FILE."
  fi
}

install_wrapper() {
  local bin_dir target source
  bin_dir="$PREFIX/bin"
  target="$bin_dir/hermes-kanban"
  source="$APP_DIR/scripts/hermes-kanban"
  run mkdir -p "$bin_dir"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY RUN: install $source -> $target"
    return
  fi
  ln -sfn "$source" "$target"
  chmod +x "$source"
  log "Installed wrapper: $target"
}

run_uv_sync() {
  if [[ "$SKIP_UV_SYNC" == "1" ]]; then
    log "Skipping uv sync"
    return
  fi
  log "Running uv sync in $APP_DIR"
  if [[ "$DRY_RUN" == "1" ]]; then
    log "DRY RUN: cd $APP_DIR && uv sync"
    return
  fi
  (cd "$APP_DIR" && uv sync)
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --prefix)
      PREFIX="${2:?--prefix requires a path}"
      shift 2
      ;;
    --app-dir)
      APP_DIR="${2:?--app-dir requires a path}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:?--env-file requires a path}"
      shift 2
      ;;
    --skip-uv-sync)
      SKIP_UV_SYNC=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

APP_DIR="$(cd "$APP_DIR" && pwd)"
PREFIX="$(python3 -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$PREFIX")"
ENV_FILE="$(python3 -c 'import os,sys; print(os.path.abspath(os.path.expanduser(sys.argv[1])))' "$ENV_FILE")"

if [[ "$DRY_RUN" == "1" ]]; then
  log "DRY RUN: install Hermes KanbanWebUI"
fi

check_app_dir
check_python
check_uv
warn_hermes_missing
write_env_file
install_wrapper
run_uv_sync

log ""
log "Hermes KanbanWebUI is installed."
log "Command : $PREFIX/bin/hermes-kanban"
log "Env     : $ENV_FILE"
log "Start   : hermes-kanban start"
log "Doctor  : hermes-kanban doctor"
log "Open    : http://127.0.0.1:8790"
